[tool.pyright]
include = [
    "**/*.py"
]
exclude = [
    "**/__pycache__",
    "**/site-packages/**",
    "**/.venv/**",
    "**/venv/**"
]
pythonVersion = "3.11"
typeCheckingMode = "strict"
reportMissingTypeStubs = "warning"
reportUnknownMemberType = "warning" 
reportUnknownVariableType = "warning"
reportUnknownArgumentType = "warning"
reportGeneralTypeIssues = "error"
reportOptionalMemberAccess = "error"
reportOptionalSubscript = "error"
reportPrivateImportUsage = "error"
reportUnnecessaryTypeIgnoreComment = "none"
reportUnnecessaryIsInstance = "warning"
reportUnnecessaryComparison = "warning"
reportConstantRedefinition = "error"
reportIncompatibleMethodOverride = "error"
reportIncompatibleVariableOverride = "error"
reportMissingParameterType = "error"
reportMissingReturnType = "error"
